import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/dev_bypass.dart';
import '../models/progress_checkin_model.dart';
import 'auth_provider.dart';
import 'elite_member_provider.dart';
import 'member_provider.dart';

// ─── Master Access Gate ───────────────────────────────────────────────────────

const _masterTiers = {
  'master', 'master_monthly', 'master_yearly',
  'Master Plan', 'Master Monthly', 'Master Yearly',
};

/// True when the member has an active Master membership.
final memberHasMasterAccessProvider =
    FutureProvider.autoDispose<bool>((ref) async {
  final user = ref.watch(currentUserProvider).value;
  if (user != null && isDevUser(user.email)) return true;

  final membership = await ref.watch(memberMembershipProvider.future);
  if (membership == null || membership.isExpired) return false;
  return _masterTiers.any(
      (t) => membership.planName.toLowerCase().contains(t.toLowerCase()));
});

// ─── Daily Adaptive Workout ───────────────────────────────────────────────────

/// Today's cached adaptive workout plan (generated by AI on demand).
final masterDailyWorkoutProvider = StateProvider<String?>((ref) => null);

// ─── Recovery Score ───────────────────────────────────────────────────────────

/// Computed recovery score 0–100 based on latest check-in energy/sleep.
final masterRecoveryScoreProvider =
    FutureProvider.autoDispose<int>((ref) async {
  final user = ref.watch(currentUserProvider).value;
  if (user == null) return 75;
  final entries = await ref.watch(eliteMuscleProgressProvider.future);
  if (entries.isEmpty) return 75;
  final latest = entries.first;
  int score = 70;
  if (latest.sleepQuality == 'excellent') {
    score += 20;
  } else if (latest.sleepQuality == 'good') {
    score += 10;
  } else if (latest.sleepQuality == 'poor') {
    score -= 10;
  }
  if (latest.energyLevel == 'high') {
    score += 10;
  } else if (latest.energyLevel == 'low') {
    score -= 10;
  }
  if (latest.adherencePercent != null) {
    score += ((latest.adherencePercent! - 50) / 10).round().clamp(-5, 5);
  }
  return score.clamp(0, 100);
});

// ─── Analytics ────────────────────────────────────────────────────────────────

/// All progress check-ins for analytics charts.
final masterAnalyticsProvider =
    FutureProvider.autoDispose<List<ProgressCheckIn>>((ref) async {
  return ref.watch(eliteMuscleProgressProvider.future);
});

// ─── Live Sessions (stub) ────────────────────────────────────────────────────

/// Upcoming live trainer session bookings (placeholder — populated from Supabase).
final masterLiveSessionsProvider =
    FutureProvider.autoDispose<List<Map<String, dynamic>>>((ref) async {
  return [];
});

// ─── Challenges (stub) ───────────────────────────────────────────────────────

/// Active gym fitness challenges (placeholder — populated from Supabase).
final masterChallengesProvider =
    FutureProvider.autoDispose<List<Map<String, dynamic>>>((ref) async {
  return [];
});
