import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../core/constants.dart';
import '../../providers/gym_provider.dart';
import '../../widgets/glassmorphic_card.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Upgrade prompt for Basic members who try to access Pro features.
class ProPaywallScreen extends ConsumerWidget {
  const ProPaywallScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final gym = ref.watch(selectedGymProvider);

    final proFeatures = [
      (Icons.smart_toy_rounded, 'AI Workout Recommendation',
          'Personalised workout plan generated by AI based on your goals'),
      (Icons.restaurant_rounded, 'AI Diet Suggestion',
          'Claude AI suggests meals and portions tailored to your macros'),
      (Icons.local_fire_department_rounded, 'Calories Tracker',
          'Log every meal and track calories burned vs consumed'),
      (Icons.pie_chart_rounded, 'Macro Tracking',
          'Daily protein, carbs, and fat breakdown with visual rings'),
      (Icons.qr_code_scanner_rounded, 'Barcode Nutrition Scanner',
          'Scan any packaged food barcode — macros auto-filled instantly'),
      (Icons.straighten_rounded, 'Body Measurements Tracking',
          'Waist, chest, arms, hips — track your transformation'),
      (Icons.show_chart_rounded, 'Progress Graphs',
          'Visual charts for weight, calories and measurements over time'),
    ];

    return Scaffold(
      backgroundColor: AppColors.bgDark,
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            backgroundColor: AppColors.bgDark,
            expandedHeight: 220,
            flexibleSpace: FlexibleSpaceBar(
              background: Container(
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                    colors: [
                      const Color(0xFFFFD700).withValues(alpha: 0.2),
                      AppColors.primary.withValues(alpha: 0.1),
                      AppColors.bgDark,
                    ],
                  ),
                ),
                child: SafeArea(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 20, vertical: 10),
                        decoration: BoxDecoration(
                          gradient: const LinearGradient(
                            colors: [Color(0xFFFFD700), Color(0xFFFF8C00)],
                          ),
                          borderRadius: BorderRadius.circular(14),
                          boxShadow: [
                            BoxShadow(
                              color: const Color(0xFFFFD700)
                                  .withValues(alpha: 0.4),
                              blurRadius: 24,
                              spreadRadius: 2,
                            ),
                          ],
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            const Icon(Icons.workspace_premium_rounded,
                                color: Colors.black, size: 22),
                            const SizedBox(width: 8),
                            Text(
                              'PRO PLAN',
                              style: GoogleFonts.inter(
                                fontSize: 18,
                                fontWeight: FontWeight.w900,
                                color: Colors.black,
                                letterSpacing: 1.5,
                              ),
                            ),
                          ],
                        ),
                      ).animate().scale(
                            duration: 600.ms,
                            curve: Curves.elasticOut,
                          ),
                      const SizedBox(height: 14),
                      Text(
                        '₹899 / month',
                        style: GoogleFonts.inter(
                          fontSize: 26,
                          fontWeight: FontWeight.w900,
                          color: AppColors.textPrimary,
                        ),
                      ).animate(delay: 200.ms).fadeIn(),
                      const SizedBox(height: 4),
                      Text(
                        'Everything in Basic + AI-powered smart features',
                        textAlign: TextAlign.center,
                        style: GoogleFonts.inter(
                            fontSize: 13, color: AppColors.textSecondary),
                      ).animate(delay: 300.ms).fadeIn(),
                    ],
                  ),
                ),
              ),
            ),
          ),

          SliverPadding(
            padding: const EdgeInsets.fromLTRB(20, 8, 20, 8),
            sliver: SliverToBoxAdapter(
              child: Text(
                'WHAT YOU GET WITH PRO',
                style: GoogleFonts.inter(
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                  color: AppColors.textMuted,
                  letterSpacing: 1.2,
                ),
              ),
            ),
          ),

          SliverPadding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            sliver: SliverToBoxAdapter(
              child: GlassmorphicCard(
                child: Padding(
                  padding: const EdgeInsets.all(8),
                  child: Column(
                    children: proFeatures.asMap().entries.map((entry) {
                      final i = entry.key;
                      final (icon, title, subtitle) = entry.value;
                      final isAI = title.startsWith('AI');
                      return Column(
                        children: [
                          ListTile(
                            contentPadding: const EdgeInsets.symmetric(
                                horizontal: 12, vertical: 4),
                            leading: Container(
                              padding: const EdgeInsets.all(8),
                              decoration: BoxDecoration(
                                gradient: isAI
                                    ? const LinearGradient(colors: [
                                        Color(0xFFFFD700),
                                        Color(0xFFFF8C00)
                                      ])
                                    : const LinearGradient(colors: [
                                        AppColors.primary,
                                        AppColors.accent
                                      ]),
                                borderRadius: BorderRadius.circular(10),
                              ),
                              child: Icon(icon,
                                  color: isAI ? Colors.black : Colors.white,
                                  size: 18),
                            ),
                            title: Text(title,
                                style: GoogleFonts.inter(
                                    fontWeight: FontWeight.w600,
                                    fontSize: 14,
                                    color: AppColors.textPrimary)),
                            subtitle: Text(subtitle,
                                style: GoogleFonts.inter(
                                    fontSize: 12,
                                    color: AppColors.textSecondary)),
                          ),
                          if (i < proFeatures.length - 1)
                            const Divider(color: AppColors.divider, height: 1),
                        ],
                      );
                    }).toList(),
                  ),
                ),
              ).animate(delay: 200.ms).fadeIn().slideY(begin: 0.04),
            ),
          ),

          SliverPadding(
            padding: const EdgeInsets.fromLTRB(20, 24, 20, 40),
            sliver: SliverToBoxAdapter(
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: [
                    const Color(0xFFFFD700).withValues(alpha: 0.1),
                    AppColors.primary.withValues(alpha: 0.06),
                  ]),
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                      color: const Color(0xFFFFD700).withValues(alpha: 0.3)),
                ),
                child: Column(
                  children: [
                    const Icon(Icons.store_rounded,
                        color: Color(0xFFFFD700), size: 32),
                    const SizedBox(height: 12),
                    Text(
                      gym?.name ?? 'Your Gym',
                      style: GoogleFonts.inter(
                          fontSize: 18,
                          fontWeight: FontWeight.w800,
                          color: AppColors.textPrimary),
                    ),
                    if (gym?.phone != null) ...[
                      const SizedBox(height: 6),
                      Text('📞 ${gym!.phone}',
                          style: GoogleFonts.inter(
                              fontSize: 14,
                              color: AppColors.textSecondary)),
                    ],
                    const SizedBox(height: 6),
                    Text(
                      'Upgrade to Pro Plan at your gym to unlock all AI features',
                      textAlign: TextAlign.center,
                      style: GoogleFonts.inter(
                          fontSize: 13, color: AppColors.textMuted),
                    ),
                  ],
                ),
              ).animate(delay: 400.ms).fadeIn(),
            ),
          ),
        ],
      ),
    );
  }
}
