-- 028_trainer_analysis_reports.sql
-- Store AI analysis reports generated by trainers for their clients

CREATE TABLE IF NOT EXISTS trainer_analysis_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trainer_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  gym_id UUID NOT NULL REFERENCES gyms(id) ON DELETE CASCADE,
  
  -- Linked plans at time of analysis
  workout_plan_id UUID REFERENCES workout_plans(id) ON DELETE SET NULL,
  diet_plan_id UUID REFERENCES diet_plans(id) ON DELETE SET NULL,
  
  -- Scores (0-100)
  overall_score INT CHECK (overall_score >= 0 AND overall_score <= 100),
  workout_adherence_score INT CHECK (workout_adherence_score >= 0 AND workout_adherence_score <= 100),
  diet_adherence_score INT CHECK (diet_adherence_score >= 0 AND diet_adherence_score <= 100),
  progress_score INT CHECK (progress_score >= 0 AND progress_score <= 100),
  consistency_score INT CHECK (consistency_score >= 0 AND consistency_score <= 100),
  
  -- Full AI response stored as JSON
  analysis_json JSONB NOT NULL,
  
  -- Summary for quick display
  summary TEXT,
  client_message TEXT,
  
  -- Metadata
  tokens_used INT DEFAULT 0,
  generation_ms INT DEFAULT 0,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_trainer_reports_client ON trainer_analysis_reports(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trainer_reports_trainer ON trainer_analysis_reports(trainer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trainer_reports_gym ON trainer_analysis_reports(gym_id, created_at DESC);

-- Enable RLS
ALTER TABLE trainer_analysis_reports ENABLE ROW LEVEL SECURITY;

-- Trainers can see and create reports they created
CREATE POLICY "Trainers see own reports" ON trainer_analysis_reports
  FOR SELECT USING (trainer_id = auth.uid());

CREATE POLICY "Trainers create reports" ON trainer_analysis_reports
  FOR INSERT WITH CHECK (trainer_id = auth.uid());

CREATE POLICY "Trainers delete own reports" ON trainer_analysis_reports
  FOR DELETE USING (trainer_id = auth.uid());

-- Members can see reports about themselves
CREATE POLICY "Members see own reports" ON trainer_analysis_reports
  FOR SELECT USING (
    client_id IN (SELECT id FROM clients WHERE user_id = auth.uid())
  );

-- Gym owners see all reports in their gym
CREATE POLICY "Owners see gym reports" ON trainer_analysis_reports
  FOR SELECT USING (
    gym_id IN (SELECT id FROM gyms WHERE owner_id = auth.uid())
  );

-- Service role has full access (for admin operations)
CREATE POLICY "Service role full access" ON trainer_analysis_reports
  FOR ALL USING (auth.role() = 'service_role');
